import { CON_SECTION } from "../../../compat/sections/con.ts";
import { runCatalog } from "./run.ts";

const PARENT_CHILD = [
  "CREATE TABLE parent (id int PRIMARY KEY)",
  "INSERT INTO parent VALUES (1), (2)",
  "CREATE TABLE child (id int, pid int REFERENCES parent(id))",
  "INSERT INTO child VALUES (10, 1)",
];

runCatalog(CON_SECTION, [
  {
    id: "CON-nn-01",
    kind: "error",
    setup: ["CREATE TABLE t (id int, v text NOT NULL)"],
    sql: "INSERT INTO t VALUES (1, NULL)",
    messageTier: "A",
  },
  {
    id: "CON-nn-02",
    kind: "error",
    setup: ["CREATE TABLE t (id int, v text NOT NULL)", "INSERT INTO t VALUES (1, 'x')"],
    sql: "UPDATE t SET v = NULL WHERE id = 1",
    messageTier: "A",
  },
  {
    id: "CON-nn-03",
    kind: "sequence",
    setup: ["CREATE TABLE t (id int, v text NOT NULL DEFAULT 'dv')"],
    steps: [{ sql: "INSERT INTO t (id) VALUES (1)" }, { sql: "SELECT id, v FROM t", query: true }],
    compareFinalState: true,
  },
  {
    id: "CON-ck-01",
    kind: "error",
    setup: ["CREATE TABLE t (n int CONSTRAINT n_pos CHECK (n > 0))"],
    sql: "INSERT INTO t VALUES (-1)",
    messageTier: "A",
  },
  {
    id: "CON-ck-02",
    kind: "sequence",
    setup: ["CREATE TABLE t (n int CHECK (n > 0))"],
    steps: [{ sql: "INSERT INTO t VALUES (NULL)" }, { sql: "SELECT n FROM t", query: true }],
    compareFinalState: true,
  },
  {
    id: "CON-ck-03",
    kind: "error",
    setup: ["CREATE TABLE t (lo int, hi int, CONSTRAINT lo_hi CHECK (lo <= hi))", "INSERT INTO t VALUES (1, 5)"],
    sql: "INSERT INTO t VALUES (9, 2)",
    messageTier: "A",
  },
  {
    id: "CON-ck-04",
    kind: "error",
    setup: ["CREATE TABLE t (n int CONSTRAINT n_pos CHECK (n > 0))", "INSERT INTO t VALUES (5)"],
    sql: "UPDATE t SET n = -5",
    messageTier: "A",
  },
  {
    id: "CON-uq-01",
    kind: "error",
    setup: ["CREATE TABLE t (v int UNIQUE)", "INSERT INTO t VALUES (1)"],
    sql: "INSERT INTO t VALUES (1)",
    messageTier: "A",
  },
  {
    id: "CON-uq-02",
    kind: "sequence",
    setup: ["CREATE TABLE t (v int UNIQUE)"],
    steps: [{ sql: "INSERT INTO t VALUES (NULL), (NULL), (1)" }, { sql: "SELECT count(*) AS n FROM t", query: true }],
    compareFinalState: true,
  },
  {
    id: "CON-uq-03",
    kind: "error",
    setup: ["CREATE TABLE t (a int, b int, UNIQUE (a, b))", "INSERT INTO t VALUES (1, 1), (1, 2)"],
    sql: "INSERT INTO t VALUES (1, 2)",
    messageTier: "A",
  },
  {
    id: "CON-pk-01",
    kind: "error",
    setup: ["CREATE TABLE t (id int PRIMARY KEY)", "INSERT INTO t VALUES (1)"],
    sql: "INSERT INTO t VALUES (1)",
    messageTier: "A",
  },
  {
    id: "CON-pk-02",
    kind: "error",
    setup: ["CREATE TABLE t (id int PRIMARY KEY)"],
    sql: "INSERT INTO t VALUES (NULL)",
    messageTier: "A",
  },
  {
    id: "CON-pk-03",
    kind: "error",
    setup: ["CREATE TABLE t (a int, b int, PRIMARY KEY (a, b))", "INSERT INTO t VALUES (1, 1), (1, 2)"],
    sql: "INSERT INTO t VALUES (1, 1)",
    messageTier: "A",
  },
  {
    id: "CON-fk-01",
    kind: "error",
    setup: PARENT_CHILD,
    sql: "INSERT INTO child VALUES (11, 99)",
    messageTier: "A",
  },
  {
    id: "CON-fk-02",
    kind: "error",
    setup: PARENT_CHILD,
    sql: "DELETE FROM parent WHERE id = 1",
    messageTier: "A",
  },
  {
    id: "CON-fk-03",
    kind: "error",
    setup: PARENT_CHILD,
    sql: "UPDATE parent SET id = 100 WHERE id = 1",
    messageTier: "A",
  },
  {
    id: "CON-fk-04",
    kind: "sequence",
    setup: [
      "CREATE TABLE parent (id int PRIMARY KEY)",
      "INSERT INTO parent VALUES (1), (2)",
      "CREATE TABLE child (id int, pid int REFERENCES parent(id) ON DELETE CASCADE)",
      "INSERT INTO child VALUES (10, 1), (11, 1), (12, 2)",
    ],
    steps: [{ sql: "DELETE FROM parent WHERE id = 1" }, { sql: "SELECT id, pid FROM child ORDER BY id", query: true }],
    compareFinalState: true,
  },
  {
    id: "CON-fk-05",
    kind: "sequence",
    setup: [
      "CREATE TABLE parent (id int PRIMARY KEY)",
      "INSERT INTO parent VALUES (1), (2)",
      "CREATE TABLE child (id int, pid int REFERENCES parent(id) ON DELETE SET NULL)",
      "INSERT INTO child VALUES (10, 1), (11, 2)",
    ],
    steps: [{ sql: "DELETE FROM parent WHERE id = 1" }, { sql: "SELECT id, pid FROM child ORDER BY id", query: true }],
    compareFinalState: true,
  },
  {
    id: "CON-fk-06",
    kind: "sequence",
    setup: [
      "CREATE TABLE parent (id int PRIMARY KEY)",
      "INSERT INTO parent VALUES (0), (1)",
      "CREATE TABLE child (id int, pid int DEFAULT 0 REFERENCES parent(id) ON DELETE SET DEFAULT)",
      "INSERT INTO child VALUES (10, 1)",
    ],
    steps: [{ sql: "DELETE FROM parent WHERE id = 1" }, { sql: "SELECT id, pid FROM child ORDER BY id", query: true }],
    compareFinalState: true,
  },
  {
    id: "CON-fk-07",
    kind: "sequence",
    setup: [
      "CREATE TABLE parent (id int PRIMARY KEY)",
      "INSERT INTO parent VALUES (1)",
      "CREATE TABLE child (id int, pid int REFERENCES parent(id) ON UPDATE CASCADE)",
      "INSERT INTO child VALUES (10, 1)",
    ],
    steps: [
      { sql: "UPDATE parent SET id = 100 WHERE id = 1" },
      { sql: "SELECT id, pid FROM child ORDER BY id", query: true },
    ],
    compareFinalState: true,
  },
  {
    id: "CON-fk-08",
    kind: "sequence",
    setup: [
      "CREATE TABLE parent (id int PRIMARY KEY)",
      "INSERT INTO parent VALUES (1)",
      "CREATE TABLE child (id int, pid int REFERENCES parent(id) ON UPDATE SET NULL)",
      "INSERT INTO child VALUES (10, 1)",
    ],
    steps: [
      { sql: "UPDATE parent SET id = 2 WHERE id = 1" },
      { sql: "SELECT id, pid FROM child ORDER BY id", query: true },
    ],
    compareFinalState: true,
  },
  {
    id: "CON-fk-09",
    kind: "error",
    setup: [
      "CREATE TABLE p (a int, b int, PRIMARY KEY (a, b))",
      "INSERT INTO p VALUES (1, 2)",
      "CREATE TABLE c (a int, b int, FOREIGN KEY (a, b) REFERENCES p (a, b))",
      "INSERT INTO c VALUES (1, 2)",
    ],
    sql: "INSERT INTO c VALUES (9, 9)",
    messageTier: "A",
  },
  {
    id: "CON-fk-10",
    kind: "sequence",
    setup: PARENT_CHILD,
    steps: [
      { sql: "INSERT INTO child VALUES (20, NULL)" },
      { sql: "SELECT id, pid FROM child ORDER BY id", query: true },
    ],
    compareFinalState: true,
  },
  {
    id: "CON-defer-01",
    kind: "error",
    setup: ["CREATE TABLE t (id int UNIQUE DEFERRABLE INITIALLY IMMEDIATE)", "INSERT INTO t VALUES (1)"],
    sql: "INSERT INTO t VALUES (1)",
    messageTier: "A",
  },
  {
    id: "CON-defer-02",
    kind: "error",
    setup: ["CREATE TABLE t (id int PRIMARY KEY DEFERRABLE INITIALLY DEFERRED)", "INSERT INTO t VALUES (1)"],
    sql: "INSERT INTO t VALUES (1)",
    messageTier: "A",
  },
  {
    id: "CON-addcon-01",
    kind: "error",
    setup: ["CREATE TABLE t (n int)", "ALTER TABLE t ADD CONSTRAINT n_pos CHECK (n > 0)"],
    sql: "INSERT INTO t VALUES (-1)",
    messageTier: "A",
  },
  {
    id: "CON-addcon-02",
    kind: "error",
    setup: [
      "CREATE TABLE t (id int)",
      "ALTER TABLE t ADD CONSTRAINT t_id_uniq UNIQUE (id)",
      "INSERT INTO t VALUES (1)",
    ],
    sql: "INSERT INTO t VALUES (1)",
    messageTier: "A",
  },
  {
    id: "CON-dropcon-01",
    kind: "sequence",
    setup: ["CREATE TABLE t (n int CONSTRAINT n_pos CHECK (n > 0))", "INSERT INTO t VALUES (1)"],
    steps: [
      { sql: "ALTER TABLE t DROP CONSTRAINT n_pos" },
      { sql: "INSERT INTO t VALUES (-1)" },
      { sql: "SELECT n FROM t ORDER BY n", query: true },
    ],
    compareFinalState: true,
  },
]);
