import { SEQ_SECTION } from "../../../compat/sections/seq.ts";
import { runCatalog } from "./run.ts";

runCatalog(SEQ_SECTION, [
  { id: "SEQ-create-01", kind: "parity", setup: ["CREATE SEQUENCE s"], sql: "SELECT nextval('s') AS v" },
  {
    id: "SEQ-create-02",
    kind: "parity",
    setup: ["CREATE SEQUENCE s START WITH 100"],
    sql: "SELECT nextval('s') AS v",
  },
  {
    id: "SEQ-create-03",
    kind: "parity",
    setup: ["CREATE SEQUENCE s INCREMENT BY 10"],
    sql: "SELECT nextval('s') AS a, nextval('s') AS b",
  },
  {
    id: "SEQ-create-04",
    kind: "parity",
    setup: ["CREATE SEQUENCE s INCREMENT BY -1"],
    sql: "SELECT nextval('s') AS a, nextval('s') AS b",
  },
  {
    id: "SEQ-create-05",
    kind: "parity",
    setup: ["CREATE SEQUENCE s START WITH 10 INCREMENT BY -2 MINVALUE 0 MAXVALUE 100"],
    sql: "SELECT nextval('s') AS a, nextval('s') AS b",
  },
  {
    id: "SEQ-cycle-01",
    kind: "parity",
    setup: ["CREATE SEQUENCE s MAXVALUE 2 CYCLE"],
    sql: "SELECT nextval('s') AS a, nextval('s') AS b, nextval('s') AS c",
  },
  {
    id: "SEQ-cycle-02",
    kind: "parity",
    setup: ["CREATE SEQUENCE s INCREMENT BY -1 MINVALUE 1 MAXVALUE 3 START 2 CYCLE"],
    sql: "SELECT nextval('s') AS a, nextval('s') AS b, nextval('s') AS c",
  },
  {
    id: "SEQ-curr-01",
    kind: "sequence",
    setup: ["CREATE SEQUENCE s"],
    steps: [
      { sql: "SELECT nextval('s') AS v", query: true },
      { sql: "SELECT currval('s') AS v", query: true },
      { sql: "SELECT nextval('s') AS v", query: true },
      { sql: "SELECT currval('s') AS v", query: true },
    ],
  },
  {
    id: "SEQ-curr-02",
    kind: "error",
    setup: ["CREATE SEQUENCE s"],
    sql: "SELECT currval('s')",
    query: true,
    messageTier: "A",
  },
  {
    id: "SEQ-setval-01",
    kind: "sequence",
    setup: ["CREATE SEQUENCE s"],
    steps: [
      { sql: "SELECT setval('s', 50) AS v", query: true },
      { sql: "SELECT nextval('s') AS v", query: true },
    ],
  },
  {
    id: "SEQ-setval-02",
    kind: "sequence",
    setup: ["CREATE SEQUENCE s"],
    steps: [
      { sql: "SELECT setval('s', 10, false) AS v", query: true },
      { sql: "SELECT nextval('s') AS v", query: true },
    ],
  },
  {
    id: "SEQ-setval-03",
    kind: "sequence",
    setup: ["CREATE SEQUENCE s"],
    steps: [
      { sql: "SELECT setval('s', 10, true) AS v", query: true },
      { sql: "SELECT nextval('s') AS v", query: true },
    ],
  },
  {
    id: "SEQ-last-01",
    kind: "sequence",
    setup: ["CREATE SEQUENCE s1", "CREATE SEQUENCE s2 START 100"],
    steps: [
      { sql: "SELECT nextval('s1') AS v", query: true },
      { sql: "SELECT lastval() AS v", query: true },
      { sql: "SELECT nextval('s2') AS v", query: true },
      { sql: "SELECT lastval() AS v", query: true },
    ],
  },
  { id: "SEQ-last-02", kind: "error", sql: "SELECT lastval()", query: true, messageTier: "A" },
  {
    id: "SEQ-serial-01",
    kind: "parity",
    setup: ["CREATE TABLE t (id serial, v text)", "INSERT INTO t (v) VALUES ('a'), ('b'), ('c')"],
    sql: "SELECT id, v FROM t ORDER BY id",
  },
  {
    id: "SEQ-serial-02",
    kind: "parity",
    setup: ["CREATE TABLE t (id bigserial, v text)", "INSERT INTO t (v) VALUES ('a'), ('b')"],
    sql: "SELECT id, v, pg_typeof(id)::text AS ty FROM t ORDER BY id",
  },
  {
    id: "SEQ-serial-03",
    kind: "parity",
    setup: [
      "CREATE TABLE t (id serial, v text)",
      "INSERT INTO t VALUES (100, 'explicit')",
      "INSERT INTO t (v) VALUES ('auto')",
    ],
    sql: "SELECT id, v FROM t ORDER BY id",
  },
  {
    id: "SEQ-serial-04",
    kind: "sequence",
    setup: ["CREATE TABLE t (id serial)"],
    steps: [
      { sql: "SELECT count(*) AS n FROM pg_class WHERE relname = 't_id_seq'", query: true },
      { sql: "DROP TABLE t" },
      { sql: "SELECT count(*) AS n FROM pg_class WHERE relname = 't_id_seq'", query: true },
    ],
  },
  {
    id: "SEQ-serial-05",
    kind: "sequence",
    setup: ["CREATE TABLE t (id serial, v text)"],
    steps: [
      { sql: "INSERT INTO t (v) VALUES ('a')" },
      { sql: "SELECT currval('t_id_seq') AS v", query: true },
      { sql: "INSERT INTO t (v) VALUES ('b')" },
      { sql: "SELECT currval('t_id_seq') AS v", query: true },
    ],
  },
  {
    id: "SEQ-ident-01",
    kind: "parity",
    setup: [
      "CREATE TABLE t (id int GENERATED BY DEFAULT AS IDENTITY, v text)",
      "INSERT INTO t (v) VALUES ('a'), ('b')",
    ],
    sql: "SELECT id, v FROM t ORDER BY id",
  },
  {
    id: "SEQ-default-01",
    kind: "parity",
    setup: [
      "CREATE SEQUENCE s",
      "CREATE TABLE t (id int DEFAULT nextval('s'), v text)",
      "INSERT INTO t (v) VALUES ('a'), ('b')",
    ],
    sql: "SELECT * FROM t ORDER BY id",
  },
  {
    id: "SEQ-drop-01",
    kind: "sequence",
    setup: ["CREATE SEQUENCE s"],
    steps: [
      { sql: "SELECT count(*) AS n FROM pg_class WHERE relname = 's'", query: true },
      { sql: "DROP SEQUENCE s" },
      { sql: "SELECT count(*) AS n FROM pg_class WHERE relname = 's'", query: true },
    ],
  },
  { id: "SEQ-drop-02", kind: "error", sql: "DROP SEQUENCE no_such_seq", messageTier: "A" },
  {
    id: "SEQ-exh-01",
    kind: "error",
    setup: ["CREATE SEQUENCE s MAXVALUE 2", "SELECT nextval('s')", "SELECT nextval('s')"],
    sql: "SELECT nextval('s')",
    query: true,
    messageTier: "A",
  },
  {
    id: "SEQ-exh-02",
    kind: "error",
    setup: [
      "CREATE SEQUENCE s INCREMENT BY -1 MINVALUE 3 MAXVALUE 5 START 4",
      "SELECT nextval('s')",
      "SELECT nextval('s')",
    ],
    sql: "SELECT nextval('s')",
    query: true,
    messageTier: "A",
  },
  {
    id: "SEQ-alter-01",
    kind: "sequence",
    setup: ["CREATE SEQUENCE s"],
    steps: [
      { sql: "SELECT nextval('s') AS a, nextval('s') AS b", query: true },
      { sql: "ALTER SEQUENCE s RESTART" },
      { sql: "SELECT nextval('s') AS v", query: true },
    ],
  },
  {
    id: "SEQ-alter-02",
    kind: "sequence",
    setup: ["CREATE SEQUENCE s"],
    steps: [
      { sql: "SELECT nextval('s') AS v", query: true },
      { sql: "ALTER SEQUENCE s INCREMENT BY 5" },
      { sql: "SELECT nextval('s') AS v", query: true },
    ],
  },
]);
