import { expect } from "bun:test";
import { TOK_SECTION } from "../../../compat/sections/tok.ts";
import { runCatalog } from "./run.ts";

runCatalog(TOK_SECTION, [
  { id: "TOK-kw-01", kind: "parity", sql: "SeLeCt 1 aS v" },
  {
    id: "TOK-ident-01",
    kind: "parity",
    setup: ['CREATE TABLE "MyTab" ("Col" int)', 'INSERT INTO "MyTab" VALUES (7)'],
    sql: 'SELECT "Col" FROM "MyTab"',
  },
  { id: "TOK-ident-02", kind: "parity", sql: 'SELECT 1 AS "a""b"' },
  {
    id: "TOK-ident-03",
    kind: "parity",
    setup: ["CREATE TABLE FooBar (XyZ int)", "INSERT INTO foobar VALUES (1)"],
    sql: "SELECT xyz FROM FOOBAR",
  },
  { id: "TOK-ident-04", kind: "parity", sql: 'SELECT 1 AS "select"' },
  { id: "TOK-ident-05", kind: "parity", sql: "SELECT 1 AS a$b_c" },
  {
    id: "TOK-ident-06",
    kind: "parity",
    setup: ['CREATE TABLE unic ("héllo" int)', "INSERT INTO unic VALUES (5)"],
    sql: 'SELECT "héllo" FROM unic',
  },
  { id: "TOK-ident-07", kind: "error", sql: 'SELECT "no_such_col"', query: true, messageTier: "A" },
  { id: "TOK-str-01", kind: "parity", sql: "SELECT 'it''s' AS v" },
  { id: "TOK-str-02", kind: "parity", sql: "SELECT 'a\nb' AS v, length('a\nb') AS n" },
  { id: "TOK-str-03", kind: "parity", sql: "SELECT '' AS v, length('') AS n" },
  { id: "TOK-str-04", kind: "parity", sql: "SELECT 'foo'\n'bar' AS v" },
  { id: "TOK-str-05", kind: "parity", sql: "SELECT 'a\\nb' AS v, length('a\\nb') AS n" },
  {
    id: "TOK-str-06",
    kind: "error",
    sql: "SELECT 'foo' 'bar' AS v",
    query: true,
    messageTier: "B",
    notes: "both raise 42601; memory names the offending token, PostgreSQL quotes the literal",
  },
  {
    id: "TOK-str-07",
    kind: "error",
    sql: "SELECT 'unterminated",
    query: true,
    messageTier: "B",
    notes: "both raise 42601 unterminated-string; PostgreSQL appends the at-or-near fragment",
  },
  { id: "TOK-estr-01", kind: "parity", sql: "SELECT E'a\\tb' AS t, e'a\\nb' AS n, length(E'a\\nb') AS len" },
  { id: "TOK-estr-02", kind: "parity", sql: "SELECT E'back\\\\slash' AS v, length(E'\\\\') AS n" },
  { id: "TOK-estr-03", kind: "parity", sql: "SELECT E'\\u00e9' AS e, E'\\u0041' AS a, length(E'\\u00e9') AS n" },
  { id: "TOK-estr-04", kind: "parity", sql: "SELECT E'\\x41' AS hex, E'\\101' AS oct" },
  { id: "TOK-dollar-01", kind: "parity", sql: 'SELECT $$don\'t "quote" me$$ AS v' },
  { id: "TOK-dollar-02", kind: "parity", sql: "SELECT $tag$a$$b$tag$ AS v, $Tag1$mixed case tag$Tag1$ AS w" },
  { id: "TOK-dollar-03", kind: "parity", sql: "SELECT $q$line1\nline2$q$ AS v" },
  { id: "TOK-num-01", kind: "parity", sql: "SELECT 1 AS i, 42 AS j, 007 AS k, pg_typeof(1)::text AS t" },
  { id: "TOK-num-02", kind: "parity", sql: "SELECT 1.5 AS a, .5 AS b, 5. AS c, pg_typeof(1.5)::text AS t" },
  { id: "TOK-num-03", kind: "parity", sql: "SELECT 1e5 AS a, 1E-5 AS b, 1.5e2 AS c, pg_typeof(1e5)::text AS t" },
  { id: "TOK-num-04", kind: "parity", sql: "SELECT 0x1A AS h" },
  { id: "TOK-num-05", kind: "parity", sql: "SELECT 1_000_000 AS v" },
  { id: "TOK-num-06", kind: "parity", sql: "SELECT 0b1010 AS b, 0o17 AS o" },
  { id: "TOK-bytea-01", kind: "parity", sql: "SELECT '\\xDEADbeef'::bytea AS v" },
  { id: "TOK-cast-01", kind: "parity", sql: "SELECT '42'::int AS a, 42::text AS b, '1.5'::float8::text AS c" },
  { id: "TOK-cmt-01", kind: "parity", sql: "SELECT 1 AS v -- trailing comment" },
  { id: "TOK-cmt-02", kind: "parity", sql: "SELECT /* block */ 2 AS v" },
  { id: "TOK-cmt-03", kind: "parity", sql: "SELECT /* outer /* nested */ still comment */ 3 AS v" },
  {
    id: "TOK-cmt-04",
    kind: "divergence",
    fn: (db) => {
      expect(() => db.exec("-- only a comment\n/* and a block */")).toThrow(/empty statement/);
    },
  },
  { id: "TOK-op-01", kind: "parity", sql: "SELECT '[1,2]'::jsonb -> 0 AS a, '{\"k\":1}'::jsonb ->> 'k' AS b" },
  {
    id: "TOK-op-02",
    kind: "parity",
    sql: "SELECT '{\"a\":1}'::jsonb @> '{}'::jsonb AS a, ARRAY[1,2] @> ARRAY[1] AS b",
  },
  { id: "TOK-op-03", kind: "parity", sql: "SELECT 3 <> 4 AS ne1, 3 != 4 AS ne2, 3 <= 3 AS le, 4 >= 3 AS ge" },
  { id: "TOK-semi-01", kind: "parity", sql: "SELECT 1 AS v;" },
  { id: "TOK-ws-01", kind: "parity", sql: "SELECT\r\n1\tAS\tv" },
  { id: "TOK-uesc-01", kind: "parity", sql: "SELECT U&'\\0441\\043B\\043E\\043D' AS v" },
]);
