import { expect } from "bun:test";
import { TXN_SECTION } from "../../../compat/sections/txn.ts";
import { runCatalog } from "./run.ts";

runCatalog(TXN_SECTION, [
  {
    id: "TXN-commit-01",
    kind: "sequence",
    setup: ["CREATE TABLE t (id int, v text)"],
    steps: [
      { sql: "BEGIN" },
      { sql: "INSERT INTO t VALUES (1, 'a'), (2, 'b')" },
      { sql: "COMMIT" },
      { sql: "SELECT * FROM t ORDER BY id", query: true },
    ],
    compareFinalState: true,
  },
  {
    id: "TXN-commit-02",
    kind: "sequence",
    setup: ["CREATE TABLE t (id int)"],
    steps: [
      { sql: "BEGIN" },
      { sql: "INSERT INTO t VALUES (10)" },
      { sql: "SELECT * FROM t ORDER BY id", query: true },
      { sql: "UPDATE t SET id = 11" },
      { sql: "SELECT * FROM t ORDER BY id", query: true },
      { sql: "COMMIT" },
    ],
    compareFinalState: true,
  },
  {
    id: "TXN-commit-03",
    kind: "sequence",
    setup: ["CREATE TABLE t (id int)"],
    steps: [
      { sql: "BEGIN" },
      { sql: "INSERT INTO t VALUES (1)" },
      { sql: "COMMIT" },
      { sql: "BEGIN" },
      { sql: "INSERT INTO t VALUES (2)" },
      { sql: "ROLLBACK" },
      { sql: "BEGIN" },
      { sql: "INSERT INTO t VALUES (3)" },
      { sql: "COMMIT" },
      { sql: "SELECT * FROM t ORDER BY id", query: true },
    ],
    compareFinalState: true,
  },
  {
    id: "TXN-rollback-01",
    kind: "sequence",
    setup: ["CREATE TABLE t (id int)"],
    steps: [
      { sql: "BEGIN" },
      { sql: "INSERT INTO t VALUES (1), (2)" },
      { sql: "ROLLBACK" },
      { sql: "SELECT count(*) AS n FROM t", query: true },
    ],
    compareFinalState: true,
  },
  {
    id: "TXN-rollback-02",
    kind: "sequence",
    setup: ["CREATE TABLE t (id int, v text)", "INSERT INTO t VALUES (1, 'orig')"],
    steps: [
      { sql: "BEGIN" },
      { sql: "UPDATE t SET v = 'changed' WHERE id = 1" },
      { sql: "SELECT v FROM t WHERE id = 1", query: true },
      { sql: "ROLLBACK" },
      { sql: "SELECT v FROM t WHERE id = 1", query: true },
    ],
    compareFinalState: true,
  },
  {
    id: "TXN-rollback-03",
    kind: "sequence",
    setup: ["CREATE TABLE t (id int)", "INSERT INTO t VALUES (1), (2), (3)"],
    steps: [
      { sql: "BEGIN" },
      { sql: "DELETE FROM t WHERE id > 1" },
      { sql: "SELECT count(*) AS n FROM t", query: true },
      { sql: "ROLLBACK" },
      { sql: "SELECT * FROM t ORDER BY id", query: true },
    ],
    compareFinalState: true,
  },
  {
    id: "TXN-ddl-01",
    kind: "sequence",
    steps: [
      { sql: "BEGIN" },
      { sql: "CREATE TABLE ddl_t (id int)" },
      { sql: "ROLLBACK" },
      { sql: "SELECT count(*) AS n FROM pg_class WHERE relname = 'ddl_t'", query: true },
    ],
  },
  {
    id: "TXN-ddl-02",
    kind: "sequence",
    steps: [
      { sql: "BEGIN" },
      { sql: "CREATE TABLE ddl_t (id int)" },
      { sql: "COMMIT" },
      { sql: "SELECT count(*) AS n FROM pg_class WHERE relname = 'ddl_t'", query: true },
    ],
  },
  {
    id: "TXN-ddl-03",
    kind: "sequence",
    setup: ["CREATE TABLE t (id int)", "INSERT INTO t VALUES (1), (2)"],
    steps: [
      { sql: "BEGIN" },
      { sql: "DROP TABLE t" },
      { sql: "ROLLBACK" },
      { sql: "SELECT * FROM t ORDER BY id", query: true },
    ],
  },
  {
    id: "TXN-ddl-04",
    kind: "sequence",
    steps: [
      { sql: "BEGIN" },
      { sql: "CREATE TABLE gone_t (id int)" },
      { sql: "INSERT INTO gone_t VALUES (1)" },
      { sql: "ROLLBACK" },
      { sql: "SELECT count(*) AS n FROM pg_class WHERE relname = 'gone_t'", query: true },
    ],
  },
  {
    id: "TXN-sp-01",
    kind: "sequence",
    setup: ["CREATE TABLE t (id int)"],
    steps: [
      { sql: "BEGIN" },
      { sql: "INSERT INTO t VALUES (1)" },
      { sql: "SAVEPOINT sp1" },
      { sql: "INSERT INTO t VALUES (2)" },
      { sql: "ROLLBACK TO sp1" },
      { sql: "COMMIT" },
      { sql: "SELECT * FROM t ORDER BY id", query: true },
    ],
    compareFinalState: true,
  },
  {
    id: "TXN-sp-02",
    kind: "sequence",
    setup: ["CREATE TABLE t (id int)"],
    steps: [
      { sql: "BEGIN" },
      { sql: "INSERT INTO t VALUES (1)" },
      { sql: "SAVEPOINT sp1" },
      { sql: "INSERT INTO t VALUES (2)" },
      { sql: "RELEASE SAVEPOINT sp1" },
      { sql: "COMMIT" },
      { sql: "SELECT * FROM t ORDER BY id", query: true },
    ],
    compareFinalState: true,
  },
  {
    id: "TXN-sp-03",
    kind: "sequence",
    setup: ["CREATE TABLE t (id int)"],
    steps: [
      { sql: "BEGIN" },
      { sql: "INSERT INTO t VALUES (1)" },
      { sql: "SAVEPOINT a" },
      { sql: "INSERT INTO t VALUES (2)" },
      { sql: "SAVEPOINT b" },
      { sql: "INSERT INTO t VALUES (3)" },
      { sql: "ROLLBACK TO a" },
      { sql: "COMMIT" },
      { sql: "SELECT * FROM t ORDER BY id", query: true },
    ],
    compareFinalState: true,
  },
  {
    id: "TXN-sp-04",
    kind: "sequence",
    setup: ["CREATE TABLE t (id int)"],
    steps: [
      { sql: "BEGIN" },
      { sql: "SAVEPOINT a" },
      { sql: "INSERT INTO t VALUES (1)" },
      { sql: "SAVEPOINT b" },
      { sql: "INSERT INTO t VALUES (2)" },
      { sql: "ROLLBACK TO b" },
      { sql: "COMMIT" },
      { sql: "SELECT * FROM t ORDER BY id", query: true },
    ],
  },
  {
    id: "TXN-sp-05",
    kind: "sequence",
    setup: ["CREATE TABLE t (id int)"],
    steps: [
      { sql: "BEGIN" },
      { sql: "INSERT INTO t VALUES (1)" },
      { sql: "SAVEPOINT a" },
      { sql: "INSERT INTO t VALUES (2)" },
      { sql: "SAVEPOINT a" },
      { sql: "INSERT INTO t VALUES (3)" },
      { sql: "ROLLBACK TO a" },
      { sql: "COMMIT" },
      { sql: "SELECT * FROM t ORDER BY id", query: true },
    ],
    compareFinalState: true,
  },
  {
    id: "TXN-sp-06",
    kind: "sequence",
    setup: ["CREATE TABLE t (id int)"],
    steps: [
      { sql: "BEGIN" },
      { sql: "SAVEPOINT sp" },
      { sql: "INSERT INTO t VALUES (1)" },
      { sql: "ROLLBACK TO sp" },
      { sql: "INSERT INTO t VALUES (2)" },
      { sql: "COMMIT" },
      { sql: "SELECT * FROM t ORDER BY id", query: true },
    ],
  },
  {
    id: "TXN-rec-01",
    kind: "sequence",
    setup: ["CREATE TABLE t (id int PRIMARY KEY)"],
    steps: [
      { sql: "BEGIN" },
      { sql: "INSERT INTO t VALUES (1)" },
      { sql: "SAVEPOINT sp" },
      { sql: "INSERT INTO t VALUES (1)" },
      { sql: "ROLLBACK TO sp" },
      { sql: "INSERT INTO t VALUES (2)" },
      { sql: "COMMIT" },
      { sql: "SELECT * FROM t ORDER BY id", query: true },
    ],
    compareFinalState: true,
  },
  {
    id: "TXN-rec-02",
    kind: "sequence",
    setup: ["CREATE TABLE t (id int)"],
    steps: [
      { sql: "BEGIN" },
      { sql: "INSERT INTO t VALUES (1)" },
      { sql: "SAVEPOINT sp" },
      { sql: "SELECT 1/0" },
      { sql: "ROLLBACK TO sp" },
      { sql: "INSERT INTO t VALUES (2)" },
      { sql: "COMMIT" },
      { sql: "SELECT * FROM t ORDER BY id", query: true },
    ],
  },
  {
    id: "TXN-edge-01",
    kind: "sequence",
    setup: ["CREATE TABLE t (id int)"],
    steps: [{ sql: "COMMIT" }, { sql: "INSERT INTO t VALUES (1)" }, { sql: "SELECT * FROM t", query: true }],
  },
  {
    id: "TXN-edge-02",
    kind: "sequence",
    setup: ["CREATE TABLE t (id int)", "INSERT INTO t VALUES (1)"],
    steps: [{ sql: "ROLLBACK" }, { sql: "SELECT * FROM t", query: true }],
  },
  {
    id: "TXN-edge-03",
    kind: "sequence",
    setup: ["CREATE TABLE t (id int)"],
    steps: [
      { sql: "BEGIN" },
      { sql: "INSERT INTO t VALUES (1)" },
      { sql: "BEGIN" },
      { sql: "INSERT INTO t VALUES (2)" },
      { sql: "ROLLBACK" },
      { sql: "SELECT count(*) AS n FROM t", query: true },
    ],
  },
  { id: "TXN-edge-04", kind: "sequence", steps: [{ sql: "SAVEPOINT sp1" }] },
  {
    id: "TXN-edge-05",
    kind: "sequence",
    setup: ["CREATE TABLE t (id int)"],
    steps: [
      { sql: "BEGIN" },
      { sql: "INSERT INTO t VALUES (1)" },
      { sql: "SELECT 1/0" },
      { sql: "ROLLBACK" },
      { sql: "SELECT count(*) AS n FROM t", query: true },
    ],
  },
  {
    id: "TXN-forms-01",
    kind: "sequence",
    setup: ["CREATE TABLE t (id int)"],
    steps: [
      { sql: "START TRANSACTION" },
      { sql: "INSERT INTO t VALUES (1)" },
      { sql: "END" },
      { sql: "SELECT * FROM t", query: true },
    ],
  },
  {
    id: "TXN-forms-02",
    kind: "sequence",
    setup: ["CREATE TABLE t (id int)"],
    steps: [
      { sql: "BEGIN WORK" },
      { sql: "INSERT INTO t VALUES (1)" },
      { sql: "COMMIT WORK" },
      { sql: "SELECT * FROM t", query: true },
    ],
  },
  {
    id: "TXN-abort-01",
    kind: "divergence",
    fn: (db) => {
      db.exec("CREATE TABLE t (id int)");
      db.exec("BEGIN");
      db.exec("INSERT INTO t VALUES (1)");
      expect(() => db.query("SELECT 1/0")).toThrow(/division by zero/);
      // PostgreSQL would reject this with 25P02; postgres-mem keeps executing.
      db.exec("INSERT INTO t VALUES (2)");
      db.exec("COMMIT");
      expect(db.query("SELECT count(*)::int AS n FROM t")[0]).toEqual({ n: 2 });
    },
  },
]);
