import { parity, parityTyped, sequenceParity } from "../helpers.ts";

parity(
  "serial column auto-increments",
  ["CREATE TABLE t (id serial, v text)", "INSERT INTO t (v) VALUES ('a'), ('b'), ('c')"],
  "SELECT id, v FROM t ORDER BY id",
);

parityTyped(
  "serial column is integer typed",
  ["CREATE TABLE t (id serial, v text)", "INSERT INTO t (v) VALUES ('a')"],
  "SELECT id FROM t",
);

parity(
  "bigserial column auto-increments and is bigint typed",
  ["CREATE TABLE t (id bigserial, v text)", "INSERT INTO t (v) VALUES ('a'), ('b')"],
  "SELECT id, v, pg_typeof(id)::text AS ty FROM t ORDER BY id",
);

parity(
  "smallserial column auto-increments",
  ["CREATE TABLE t (id smallserial, v text)", "INSERT INTO t (v) VALUES ('a'), ('b')"],
  "SELECT id, v FROM t ORDER BY id",
);

parity(
  "explicit value bypasses the serial default",
  ["CREATE TABLE t (id serial, v text)", "INSERT INTO t VALUES (100, 'explicit')", "INSERT INTO t (v) VALUES ('auto')"],
  "SELECT id, v FROM t ORDER BY id",
);

sequenceParity(
  "serial backing sequence is dropped with the table",
  ["CREATE TABLE t (id serial)"],
  [
    { sql: "SELECT count(*) AS n FROM pg_class WHERE relname = 't_id_seq'", query: true },
    { sql: "DROP TABLE t" },
    { sql: "SELECT count(*) AS n FROM pg_class WHERE relname = 't_id_seq'", query: true },
  ],
);

sequenceParity(
  "OWNED BY sequence is dropped with its table",
  ["CREATE TABLE t (id int)", "CREATE SEQUENCE s OWNED BY t.id"],
  [
    { sql: "SELECT count(*) AS n FROM pg_class WHERE relname = 's'", query: true },
    { sql: "DROP TABLE t" },
    { sql: "SELECT count(*) AS n FROM pg_class WHERE relname = 's'", query: true },
  ],
);

sequenceParity(
  "OWNED BY NONE detaches the sequence from the table",
  ["CREATE TABLE t (id int)", "CREATE SEQUENCE s OWNED BY t.id"],
  [
    { sql: "ALTER SEQUENCE s OWNED BY NONE" },
    { sql: "DROP TABLE t" },
    { sql: "SELECT count(*) AS n FROM pg_class WHERE relname = 's'", query: true },
  ],
);

parity(
  "serial sequence visible in pg_class",
  ["CREATE TABLE t (id serial)"],
  "SELECT relname, relkind FROM pg_class WHERE relname = 't_id_seq'",
);

sequenceParity(
  "currval usable after serial insert",
  ["CREATE TABLE t (id serial, v text)"],
  [
    { sql: "INSERT INTO t (v) VALUES ('a')" },
    { sql: "SELECT currval('t_id_seq') AS v", query: true },
    { sql: "INSERT INTO t (v) VALUES ('b')" },
    { sql: "SELECT currval('t_id_seq') AS v", query: true },
  ],
);

parity(
  "GENERATED BY DEFAULT AS IDENTITY auto-increments",
  ["CREATE TABLE t (id int GENERATED BY DEFAULT AS IDENTITY, v text)", "INSERT INTO t (v) VALUES ('a'), ('b')"],
  "SELECT id, v FROM t ORDER BY id",
);
