import { type CatalogSection, section } from "../scenario-types.ts";

export const AGG_SECTION: CatalogSection = section("AGG", "Aggregate functions", true, [
  ["cnt-01", "count star column constant and NULL"],
  ["cnt-02", "count DISTINCT incl row values"],
  ["sum-01", "sum over ints numerics floats"],
  ["sum-02", "sum and avg result types"],
  ["sum-03", "bigint sum avoids overflow via numeric"],
  ["avg-01", "avg over ints and filters nulls"],
  ["minmax-01", "min max over ints and text"],
  ["minmax-02", "min max over dates and intervals"],
  ["empty-01", "aggregates over an empty table"],
  ["empty-02", "aggregates over all-NULL input"],
  ["str-01", "string_agg with ORDER BY and delimiters"],
  ["str-02", "string_agg NULL handling and NULL separator"],
  ["str-03", "string_agg per group"],
  ["arr-01", "array_agg ordered incl NULLs"],
  ["arr-02", "array_agg empty input and per group"],
  ["jsn-01", "json_agg and jsonb_agg"],
  ["jsn-02", "json_object_agg and jsonb_object_agg"],
  ["bool-01", "bool_and bool_or every"],
  ["bool-02", "bool aggregates over empty input"],
  ["bit-01", "bit_and bit_or bit_xor"],
  ["dist-01", "DISTINCT inside sum and avg"],
  ["dist-02", "DISTINCT inside string_agg and array_agg"],
  ["fil-01", "FILTER WHERE on aggregates"],
  ["fil-02", "FILTER with GROUP BY"],
  ["fil-03", "FILTER excluding all rows and with DISTINCT"],
  ["grp-01", "GROUP BY with HAVING"],
  ["grp-02", "GROUP BY expression"],
  ["grp-03", "aggregates over joins"],
  ["std-01", "stddev family"],
  ["std-02", "variance family"],
  ["std-03", "stddev variance degenerate inputs"],
  ["pct-01", "percentile_cont median and interpolation"],
  ["pct-02", "percentile_disc and bounds"],
  ["pct-03", "percentile over empty input"],
  ["mode-01", "mode and tie-breaking"],
  ["corr-01", "corr and covariance"],
  ["corr-02", "linear regression family"],
  ["expr-01", "aggregates inside expressions and CASE"],
  ["ord-01", "ORDER BY inside plain aggregates"],
  ["sub-01", "aggregate in a correlated subquery"],
  ["err-01", "undefined column inside aggregate errors"],
]);
