import { type CatalogSection, section } from "../scenario-types.ts";

export const ARR_SECTION: CatalogSection = section("ARR", "Arrays", true, [
  ["lit-01", "ARRAY constructor int and text"],
  ["lit-02", "text literal input incl quoted elements"],
  ["lit-03", "empty arrays typed"],
  ["lit-04", "NULL elements rendering"],
  ["lit-05", "expression elements and coercion"],
  ["lit-06", "multi-dim constructor and literal"],
  ["lit-07", "ARRAY from a subquery"],
  ["sub-01", "one-based subscripting"],
  ["sub-02", "out-of-range zero negative subscripts are NULL"],
  ["sub-03", "column and expression subscripts"],
  ["sub-04", "multi-dim subscripts and partial access"],
  ["slice-01", "basic slices"],
  ["slice-02", "open-ended slices"],
  ["slice-03", "clamped and empty slices"],
  ["slice-04", "multi-dim slices"],
  ["meta-01", "array_length and cardinality"],
  ["meta-02", "array_dims ndims upper lower"],
  ["srf-01", "unnest in FROM"],
  ["srf-02", "unnest in the SELECT list"],
  ["srf-03", "unnest WITH ORDINALITY"],
  ["srf-04", "multi-argument unnest"],
  ["srf-05", "generate_subscripts forward and reverse"],
  ["agg-01", "array_agg with ORDER BY and DISTINCT"],
  ["agg-02", "unnest array_agg round trip per group"],
  ["op-01", "|| concatenation element and array forms"],
  ["op-02", "@> and <@ containment"],
  ["op-03", "&& overlap"],
  ["op-04", "equality and lexicographic ordering"],
  ["op-05", "comparisons with NULL elements"],
  ["fn-01", "array_append prepend cat"],
  ["fn-02", "array_remove and array_replace"],
  ["fn-03", "array_position and array_positions"],
  ["fn-04", "array_to_string with NULL handling"],
  ["fn-05", "string_to_array with null token"],
  ["fn-06", "array_fill and trim_array"],
  ["any-01", "ANY over arrays"],
  ["any-02", "ALL and non-equality operators"],
  ["where-01", "array predicates filter rows in WHERE"],
  ["store-01", "stored arrays in GROUP BY and DISTINCT"],
  ["err-01", "malformed array literal errors"],
  ["err-02", "ragged multi-dim constructor errors"],
]);
