import { type CatalogSection, section } from "../scenario-types.ts";

export const CON_SECTION: CatalogSection = section("CON", "Constraints & enforcement", true, [
  ["nn-01", "NOT NULL violation on INSERT (23502)"],
  ["nn-02", "NOT NULL violation on UPDATE"],
  ["nn-03", "DEFAULT satisfies NOT NULL"],
  ["ck-01", "named CHECK violation on INSERT (23514)"],
  ["ck-02", "CHECK evaluating to NULL passes"],
  ["ck-03", "table-level multi-column CHECK"],
  ["ck-04", "CHECK enforced on UPDATE"],
  ["uq-01", "UNIQUE violation on INSERT (23505)"],
  ["uq-02", "UNIQUE allows multiple NULLs"],
  ["uq-03", "composite UNIQUE blocks full duplicates only"],
  ["pk-01", "PRIMARY KEY duplicate violation"],
  ["pk-02", "PRIMARY KEY rejects NULL (23502)"],
  ["pk-03", "composite PRIMARY KEY"],
  ["fk-01", "FK insert violation (23503)"],
  ["fk-02", "parent DELETE blocked by default NO ACTION"],
  ["fk-03", "parent key UPDATE blocked by FK"],
  ["fk-04", "ON DELETE CASCADE"],
  ["fk-05", "ON DELETE SET NULL"],
  ["fk-06", "ON DELETE SET DEFAULT"],
  ["fk-07", "ON UPDATE CASCADE"],
  ["fk-08", "ON UPDATE SET NULL"],
  ["fk-09", "composite FK violation"],
  ["fk-10", "NULL child reference bypasses FK"],
  ["defer-01", "DEFERRABLE INITIALLY IMMEDIATE still enforces"],
  ["defer-02", "DEFERRABLE INITIALLY DEFERRED parses and enforces outside txn"],
  ["addcon-01", "ALTER TABLE ADD CONSTRAINT CHECK is enforced"],
  ["addcon-02", "ALTER TABLE ADD CONSTRAINT UNIQUE is enforced"],
  ["dropcon-01", "DROP CONSTRAINT lifts enforcement"],
]);
