import { type CatalogSection, section } from "../scenario-types.ts";

export const CTE_SECTION: CatalogSection = section("CTE", "Common table expressions", true, [
  ["basic-01", "basic WITH"],
  ["cols-01", "CTE column-alias list"],
  ["multi-01", "multiple CTEs in one WITH"],
  ["chain-01", "CTE references an earlier CTE"],
  ["ref-01", "CTE referenced multiple times"],
  ["shadow-01", "CTE shadows a real table"],
  ["mat-01", "MATERIALIZED hint"],
  ["mat-02", "NOT MATERIALIZED hint"],
  ["nest-01", "CTE referenced from a subquery"],
  ["agg-01", "aggregate over a CTE"],
  ["set-01", "CTEs feeding a set operation"],
  ["err-01", "forward CTE reference errors"],
  ["err-02", "self-reference without RECURSIVE errors"],
  ["err-03", "too many CTE column aliases errors"],
  ["rec-01", "WITH RECURSIVE integer series"],
  ["rec-02", "recursive UNION dedup terminates cycles"],
  ["rec-03", "recursive tree walk with depth"],
  ["rec-04", "recursive path accumulation"],
  ["rec-05", "recursion terminated by WHERE"],
  ["rec-06", "LIMIT over a recursive result"],
  ["rec-07", "multi-column recursion"],
  ["dml-01", "WITH INSERT RETURNING read by outer SELECT"],
  ["dml-02", "WITH UPDATE RETURNING read by outer SELECT"],
  ["dml-03", "WITH DELETE RETURNING read by outer SELECT"],
  ["dml-04", "modifying CTE feeding an INSERT"],
]);
