import { type CatalogSection, section } from "../scenario-types.ts";

const D = "documented_divergence" as const;

export const DAT_SECTION: CatalogSection = section("DAT", "Date/time types & intervals", true, [
  ["lit-01", "date literals and text casts"],
  ["lit-02", "timestamp literals incl fractional seconds and T separator"],
  ["lit-03", "time literals"],
  ["lit-04", "timestamptz literals and offset normalization"],
  ["lit-05", "special values epoch and infinity"],
  ["cast-01", "casts among date timestamp time"],
  ["ex-01", "extract date and time fields"],
  ["ex-02", "extract dow isodow doy week"],
  ["ex-03", "extract quarter century decade millennium"],
  ["ex-04", "extract isoyear at year boundary"],
  ["ex-05", "extract epoch from timestamp date interval"],
  ["ex-06", "extract vs date_part result types"],
  ["ex-07", "extract fields from intervals"],
  ["trunc-01", "date_trunc fine fields"],
  ["trunc-02", "date_trunc coarse fields"],
  ["trunc-03", "date_trunc on interval"],
  ["age-01", "age of two timestamps both directions"],
  ["arith-01", "date plus/minus integer days"],
  ["arith-02", "date arithmetic result types"],
  ["arith-03", "timestamp plus/minus interval"],
  ["arith-04", "timestamp difference is interval"],
  ["arith-05", "month-end clamping and leap-year arithmetic"],
  ["arith-06", "time plus interval wraps midnight"],
  ["iv-01", "interval unit literals plural and abbreviated"],
  ["iv-02", "SQL-standard and ISO 8601 interval input"],
  ["iv-03", "mixed-sign interval formatting and ago"],
  ["iv-04", "fractional interval units spill down"],
  ["iv-05", "interval addition subtraction negation"],
  ["iv-06", "interval multiplication and division"],
  ["iv-07", "interval comparisons across units"],
  ["just-01", "justify_hours and justify_days"],
  ["just-02", "justify_interval and negative inputs"],
  ["mk-01", "make_date and make_time"],
  ["mk-02", "make_timestamp and make_timestamptz"],
  ["mk-03", "make_interval positional and named"],
  ["fmt-01", "to_char date and time patterns"],
  ["fmt-02", "to_char on intervals"],
  ["fmt-03", "to_date parsing"],
  ["ovl-01", "OVERLAPS operator half-open semantics"],
  ["fin-01", "isfinite on date timestamp interval"],
  ["edge-01", "year one and century boundaries"],
  ["ord-01", "ORDER BY date and interval columns"],
  [
    "now-01",
    "now/current_date fixed to 2000-01-01",
    D,
    "deterministic fixed now",
    ["tests/contract/determinism/"],
    "deterministic-runtime",
  ],
  ["err-01", "out-of-range date fields error"],
  ["err-02", "garbage date text errors"],
  ["err-03", "invalid time errors"],
  ["err-04", "invalid interval text errors"],
]);
