import { type CatalogSection, section } from "../scenario-types.ts";

const D = "documented_divergence" as const;

export const DDL_SECTION: CatalogSection = section("DDL", "Schema definition", true, [
  ["ct-01", "CREATE TABLE with common column types"],
  ["ct-02", "column defaults including expressions"],
  ["ct-03", "CREATE TABLE IF NOT EXISTS is idempotent"],
  ["ct-04", "duplicate table name errors"],
  ["ct-05", "quoted mixed-case identifiers"],
  ["ctas-01", "CREATE TABLE AS SELECT"],
  ["ctas-02", "CTAS WITH NO DATA keeps shape only"],
  ["ctas-03", "CTAS column name overrides"],
  ["drop-01", "DROP TABLE and DROP TABLE IF EXISTS"],
  ["drop-02", "DROP of a missing table errors"],
  [
    "drop-03",
    "DROP TABLE CASCADE leaves dependent views behind",
    D,
    "oracle drops the dependent view; memory keeps a broken view (see tests/contract/_reports/catalog-querydml.md)",
    undefined,
    "drop-cascade-view-retained",
  ],
  ["alter-01", "ADD COLUMN with default backfills rows"],
  ["alter-02", "DROP COLUMN removes data and star output"],
  ["alter-03", "RENAME COLUMN"],
  ["alter-04", "RENAME TABLE"],
  ["view-01", "CREATE VIEW and query through it"],
  ["view-02", "view column-alias list"],
  ["view-03", "view on view"],
  ["view-04", "CREATE OR REPLACE VIEW swaps definition"],
  ["view-05", "DROP VIEW and IF EXISTS"],
  ["idx-01", "CREATE INDEX never changes results"],
  ["idx-02", "UNIQUE INDEX rejects duplicates"],
  ["idx-03", "partial unique index scopes enforcement"],
  ["idx-04", "expression unique index"],
  ["idx-05", "DROP INDEX lifts enforcement"],
  ["schema-01", "CREATE SCHEMA with qualified tables"],
  ["schema-02", "DROP SCHEMA CASCADE"],
  ["temp-01", "temp table lifecycle"],
  ["enum-01", "CREATE TYPE AS ENUM ordering and usage"],
  ["enum-02", "invalid enum literal errors"],
  ["domain-01", "CREATE DOMAIN accepted values"],
  ["domain-02", "domain CHECK violation errors"],
  ["gen-01", "generated STORED column on insert"],
  ["gen-02", "generated column recomputes on UPDATE"],
  [
    "comment-01",
    "COMMENT ON TABLE parses but is not stored",
    D,
    "oracle stores the comment; memory obj_description(oid) returns NULL (see tests/contract/_reports/catalog-querydml.md)",
    undefined,
    "comment-on-not-stored",
  ],
]);
