import { type CatalogSection, section } from "../scenario-types.ts";

export const DML_SECTION: CatalogSection = section("DML", "Data modification", true, [
  ["ins-01", "single-row INSERT"],
  ["ins-02", "multi-row VALUES INSERT"],
  ["ins-03", "INSERT ... SELECT"],
  ["ins-04", "INSERT ... SELECT from the same table"],
  ["ins-05", "INSERT DEFAULT VALUES"],
  ["ins-06", "DEFAULT keyword inside VALUES"],
  ["ins-07", "column list reorders values"],
  ["ins-08", "zero-row INSERT ... SELECT command tag"],
  ["ret-01", "INSERT RETURNING *"],
  ["ret-02", "INSERT RETURNING expressions"],
  ["ret-03", "UPDATE RETURNING"],
  ["ret-04", "DELETE RETURNING"],
  ["upd-01", "UPDATE with expressions"],
  ["upd-02", "UPDATE row count for WHERE subset"],
  ["upd-03", "UPDATE all rows command tag"],
  ["upd-04", "UPDATE ... FROM join"],
  ["upd-05", "UPDATE SET (a, b) = row literal"],
  ["upd-06", "UPDATE SET (a, b) = scalar subquery row"],
  ["upd-07", "zero-row UPDATE command tag"],
  ["del-01", "DELETE with WHERE"],
  ["del-02", "DELETE all rows command tag"],
  ["del-03", "DELETE USING join"],
  ["del-04", "zero-row DELETE command tag"],
  ["conf-01", "ON CONFLICT DO NOTHING without target"],
  ["conf-02", "ON CONFLICT (col) DO NOTHING"],
  ["conf-03", "DO UPDATE with EXCLUDED"],
  ["conf-04", "DO UPDATE referencing the existing row"],
  ["conf-05", "DO UPDATE with WHERE clause"],
  ["conf-06", "ON CONFLICT ON CONSTRAINT target"],
  ["conf-07", "composite conflict target"],
  ["conf-08", "upsert RETURNING"],
  ["trunc-01", "TRUNCATE empties the table"],
  ["trunc-02", "TRUNCATE RESTART IDENTITY resets sequences"],
]);
