import { type CatalogSection, section } from "../scenario-types.ts";

const D = "documented_divergence" as const;

export const EXP_SECTION: CatalogSection = section("EXP", "Expressions & operators", true, [
  ["arith-01", "Integer division truncates toward zero"],
  ["arith-02", "Modulo sign follows dividend"],
  ["arith-03", "Integer division by zero errors"],
  ["arith-04", "Modulo by zero errors"],
  ["arith-05", "Numeric division by zero errors"],
  ["arith-06", "Arithmetic across mixed types"],
  ["arith-07", "Exponentiation operator ^"],
  ["concat-01", "|| with NULL yields NULL"],
  ["concat-02", "|| with non-text operands"],
  ["concat-03", "integer || integer errors"],
  ["null-01", "Comparisons with NULL yield NULL"],
  ["dist-01", "IS DISTINCT FROM / IS NOT DISTINCT FROM"],
  ["between-01", "BETWEEN and BETWEEN SYMMETRIC"],
  ["between-02", "BETWEEN with NULL bounds"],
  ["in-01", "IN lists with NULL"],
  ["in-02", "IN subquery with NULL rows"],
  [
    "in-03",
    "Row-value IN subquery",
    D,
    "memory rejects multi-column row-value IN (SELECT ...) with 'subquery has too many columns'; PostgreSQL evaluates it",
    undefined,
    "row-value-subquery-arity",
  ],
  ["case-01", "CASE with NULL condition takes ELSE"],
  ["case-02", "CASE evaluates branches lazily"],
  ["cond-01", "COALESCE"],
  ["cond-02", "NULLIF"],
  ["cond-03", "GREATEST and LEAST ignore NULLs"],
  ["bool-01", "Three-valued AND/OR/NOT"],
  ["bool-02", "IS TRUE / IS FALSE / IS UNKNOWN"],
  ["like-01", "LIKE case sensitivity vs ILIKE"],
  ["like-02", "LIKE ESCAPE and default backslash escape"],
  ["like-03", "LIKE with NULL operands"],
  ["similar-01", "SIMILAR TO patterns"],
  ["regex-01", "POSIX regex ~ ~* !~ !~*"],
  ["regex-02", "Regex classes and word boundaries"],
  ["regex-03", "Invalid regex errors"],
  ["arrsub-01", "Array subscripting and out-of-bounds NULL"],
  ["arrsub-02", "Array slices and matrix subscripts"],
  ["scalar-01", "Scalar subquery with zero rows is NULL"],
  ["scalar-02", "Scalar subquery with many rows errors"],
  ["cmp-01", "Text comparison ordering"],
  ["cmp-02", "Cross-width numeric equality"],
  ["unary-01", "Unary plus and minus"],
  ["bit-01", "Bitwise operators on integers"],
  ["any-01", "ANY and ALL over arrays"],
]);
