import { type CatalogSection, section } from "../scenario-types.ts";

const D = "documented_divergence" as const;

export const FUN_SECTION: CatalogSection = section("FUN", "Built-in scalar functions", true, [
  ["length-01", "length/char_length/octet_length/bit_length"],
  ["case-01", "upper/lower/initcap"],
  ["substr-01", "substr and substring forms"],
  ["substr-02", "Negative substring length errors"],
  ["trim-01", "trim/ltrim/rtrim/btrim with custom sets"],
  ["pad-01", "lpad/rpad including truncation"],
  ["replace-01", "replace and translate"],
  ["split-01", "split_part including negative index"],
  ["strpos-01", "strpos and position"],
  ["leftright-01", "left/right including negative counts"],
  ["repeat-01", "repeat and reverse"],
  ["format-01", "format %s %I %L, positional and NULL args"],
  ["concat-01", "concat and concat_ws NULL handling"],
  ["regexp-01", "regexp_replace flags and backreferences"],
  ["regexp-02", "regexp_matches as scalar"],
  ["regexp-03", "regexp_split_to_array"],
  ["regexp-04", "regexp_count/regexp_like/regexp_substr"],
  ["abs-01", "abs across types"],
  ["ceil-01", "ceil/ceiling/floor"],
  ["round-01", "round numeric including 2-arg and ties"],
  [
    "round-02",
    "round float8 ties",
    D,
    "memory rounds float8 ties away from zero (round(2.5::float8) = 3); PostgreSQL rounds half to even (= 2)",
    undefined,
    "round-half-away-from-zero",
  ],
  ["trunc-01", "trunc 1-arg and 2-arg"],
  ["sign-01", "sign across types"],
  ["moddiv-01", "mod and div sign rules"],
  ["exp-01", "exp on float8 and numeric"],
  ["ln-01", "ln on float8 and numeric"],
  ["ln-02", "ln of negative errors"],
  ["log-01", "log/log10 and 2-arg log"],
  ["sqrt-01", "sqrt/cbrt on float8 and numeric"],
  ["sqrt-02", "sqrt of negative errors"],
  ["power-01", "power on float8 and numeric"],
  ["trig-01", "Trigonometric functions"],
  ["trig-02", "asin out of range errors"],
  ["trig-03", "Degree-based trig sind/cosd/tand"],
  ["pi-01", "pi/degrees/radians"],
  ["wb-01", "width_bucket including out-of-range inputs"],
  ["tochar-01", "to_char numeric templates"],
  ["tochar-02", "to_char sign and FM modifiers"],
  ["md5-01", "md5"],
  ["encode-01", "encode hex/base64/escape"],
  ["decode-01", "decode hex and base64"],
  ["decode-02", "decode invalid hex errors"],
  ["gcd-01", "gcd and lcm"],
  ["fact-01", "factorial"],
  ["nulls-01", "num_nonnulls and num_nulls"],
]);
