import { type CatalogSection, section } from "../scenario-types.ts";

export const JOI_SECTION: CatalogSection = section("JOI", "Joins & lateral", true, [
  ["inner-01", "INNER JOIN ON equality"],
  ["inner-02", "join on expression"],
  ["comma-01", "implicit comma join with WHERE"],
  ["cross-01", "CROSS JOIN"],
  ["left-01", "LEFT JOIN NULL padding"],
  ["left-02", "extra filter in ON keeps unmatched left rows"],
  ["left-03", "filter in WHERE turns LEFT JOIN into inner"],
  ["right-01", "RIGHT JOIN NULL padding"],
  ["full-01", "FULL JOIN pads both sides"],
  ["using-01", "USING dedups join column in star"],
  ["using-02", "qualified and bare join column after USING"],
  ["natural-01", "NATURAL JOIN on common columns"],
  ["natural-02", "NATURAL LEFT JOIN"],
  ["natural-03", "NATURAL join with no common columns is a cross product"],
  ["chain-01", "three-table join chain"],
  ["paren-01", "parenthesized join tree"],
  ["self-01", "self-join with aliases"],
  ["mixed-01", "mixed INNER and LEFT joins"],
  ["lat-01", "LATERAL generate_series"],
  ["lat-02", "LATERAL unnest of an array column"],
  ["lat-03", "LATERAL correlated subquery with LIMIT"],
  ["lat-04", "LEFT JOIN LATERAL ON true keeps unmatched rows"],
  ["semi-01", "semi-join via EXISTS"],
  ["anti-01", "anti-join via NOT EXISTS"],
  ["multi-01", "three-plus-table join with aggregate"],
  ["expr-01", "join on range condition"],
  ["outer-01", "aggregate over outer-join NULL padding"],
  ["err-01", "ambiguous column in join errors"],
  ["err-02", "USING column missing from one side errors"],
]);
