import { type CatalogSection, section } from "../scenario-types.ts";

export const JSN_SECTION: CatalogSection = section("JSN", "JSON & JSONB", true, [
  ["rt-01", "jsonb canonicalizes key order"],
  ["rt-02", "jsonb deduplicates keys keeping the last"],
  ["rt-03", "json preserves order duplicates whitespace"],
  ["rt-04", "jsonb::text round trip"],
  ["rt-05", "jsonb number canonicalization"],
  ["rt-06", "json <-> jsonb conversions"],
  ["rt-07", "jsonb scalars and json null vs SQL NULL"],
  ["rt-08", "nested structures and unicode escapes"],
  ["rt-09", "jsonb column round trips through storage"],
  ["op-01", "-> field and array index access"],
  ["op-02", "->> text access and negative index"],
  ["op-03", "missing key or index yields NULL"],
  ["op-04", "#> and #>> nested path access"],
  ["op-05", "@> containment object array nested"],
  ["op-06", "<@ contained by"],
  ["op-07", "? ?| ?& existence operators"],
  ["op-08", "|| concatenation of objects arrays scalars"],
  ["op-09", "- deletion by key index and key array"],
  ["op-10", "#- nested path deletion"],
  ["eq-01", "jsonb equality is structural"],
  ["fn-01", "jsonb_set replace add nested and array index"],
  ["fn-02", "jsonb_insert at array positions"],
  ["fn-03", "strip_nulls for json and jsonb"],
  ["fn-04", "jsonb_pretty formatting"],
  ["fn-05", "typeof for json and jsonb kinds"],
  ["fn-06", "array_length for json and jsonb"],
  ["fn-07", "jsonb_object_keys"],
  ["fn-08", "each and each_text set-returning"],
  ["fn-09", "array_elements and _text with ordinality"],
  ["fn-10", "extract_path and extract_path_text"],
  ["fn-11", "build_object and build_array json and jsonb"],
  ["fn-12", "jsonb_object from a text array"],
  ["fn-13", "to_json to_jsonb row_to_json"],
  ["cast-01", "jsonb scalar casts to int and boolean"],
  ["agg-01", "json_agg and jsonb_agg ordered"],
  ["agg-02", "json_object_agg and jsonb_object_agg"],
  ["agg-03", "json aggregates over empty input are NULL"],
  ["where-01", "containment filters rows in WHERE"],
  ["err-01", "invalid json text errors"],
  ["err-02", "trailing garbage after valid json errors"],
  ["err-03", "jsonb_array_length on an object errors"],
  ["err-04", "empty string is not valid json"],
]);
