import { type CatalogSection, section } from "../scenario-types.ts";

const D = "documented_divergence" as const;

export const PAR_SECTION: CatalogSection = section("PAR", "Parser & grammar", true, [
  ["prec-01", "Exponentiation associativity and unary minus"],
  ["prec-02", "OR binds looser than AND"],
  ["prec-03", "NOT binds looser than comparison"],
  ["prec-04", "IS NULL binds looser than +"],
  ["prec-05", "BETWEEN binds looser than +"],
  ["prec-06", ":: binds tighter than unary minus"],
  ["prec-07", "^ with negative exponent"],
  ["case-01", "Simple CASE expression"],
  ["case-02", "Searched CASE expression"],
  ["case-03", "CASE without ELSE yields NULL"],
  ["row-01", "Row constructor equality"],
  ["row-02", "Row constructor ordering"],
  [
    "row-03",
    "Row constructor size mismatch",
    D,
    "memory raises 21000 cardinality at execution; PostgreSQL raises 42601 syntax at parse time",
  ],
  ["arr-01", "ARRAY[...] constructor"],
  ["arr-02", "Nested ARRAY constructor"],
  ["arr-03", "ARRAY element type mismatch errors"],
  ["cast-01", "CAST(x AS t) equals x::t"],
  ["fetch-01", "FETCH FIRST n ROWS ONLY"],
  ["fetch-02", "OFFSET with FETCH NEXT"],
  ["fetch-03", "FETCH FIRST WITH TIES"],
  ["limit-01", "LIMIT and OFFSET"],
  ["sub-01", "Parenthesized subquery in FROM"],
  ["exists-01", "EXISTS and NOT EXISTS"],
  ["in-01", "IN and NOT IN value lists"],
  ["multi-01", "Multi-statement exec script"],
  ["syntax-01", "Unknown leading keyword errors"],
  ["syntax-02", "Unbalanced parentheses error"],
  ["syntax-03", "Dangling comma in select list errors"],
  ["values-01", "Standalone VALUES statement"],
  ["values-02", "VALUES as table expression with aliases"],
  ["distinct-01", "SELECT DISTINCT"],
  ["ord-01", "ORDER BY with NULLS FIRST/LAST"],
  ["grp-01", "GROUP BY with HAVING"],
  ["alias-01", "Optional AS in aliases"],
  ["typedlit-01", "Typed literals date and timestamp"],
  ["typedlit-02", "INTERVAL literal forms"],
  ["typedlit-03", "Invalid typed literal errors"],
  ["param-01", "Positional $n parameters"],
  ["depth-01", "Deeply nested parentheses"],
  ["reserved-01", "Reserved words misused as identifiers error"],
  [
    "neg-01",
    "Nested unary minus on numeric literals",
    D,
    "memory folds repeated unary minus into the literal text and rejects it; PostgreSQL evaluates - -5 to 5",
  ],
]);
