import { type CatalogSection, section } from "../scenario-types.ts";

export const SCH_SECTION: CatalogSection = section("SCH", "Schemas and search_path", true, [
  ["create-01", "CREATE SCHEMA and a table inside it"],
  ["create-02", "CREATE SCHEMA IF NOT EXISTS is idempotent"],
  ["create-03", "schema appears in pg_namespace"],
  ["qual-01", "schema-qualified insert, update, select"],
  ["qual-02", "schema-qualified delete"],
  ["dup-01", "same table name in two schemas holds separate data"],
  ["join-01", "join across schemas"],
  ["seq-01", "sequence inside a schema"],
  ["view-01", "view inside a schema"],
  ["fk-01", "cross-schema foreign key enforced"],
  ["drop-01", "DROP SCHEMA removes an empty schema"],
  ["drop-02", "DROP SCHEMA without CASCADE fails when non-empty"],
  ["drop-03", "DROP SCHEMA CASCADE removes contained tables"],
  ["drop-04", "DROP SCHEMA CASCADE removes sequences and views"],
  ["drop-05", "DROP SCHEMA IF EXISTS on a missing schema is a no-op"],
  ["drop-06", "dropping one schema leaves the same-named table elsewhere"],
  ["path-01", "search_path picks the first schema containing the table"],
  ["path-02", "resolution falls through schemas missing the table"],
  ["path-03", "CREATE TABLE goes to the first schema on the search_path"],
  ["path-04", "current_schema reflects the first search_path entry"],
  ["path-05", "qualified names bypass the search_path"],
  ["path-06", "current_schemas lists the effective path"],
  ["cat-01", "pg_catalog builtins visible regardless of search_path"],
  ["cat-02", "pg_catalog tables visible regardless of search_path"],
  ["alter-01", "ALTER TABLE SET SCHEMA moves the table"],
  ["err-01", "CREATE TABLE in a missing schema fails with 3F000"],
  ["err-02", "duplicate schema fails with 42P06"],
]);
