import { type CatalogSection, section } from "../scenario-types.ts";

export const SEL_SECTION: CatalogSection = section("SEL", "SELECT surface", true, [
  ["proj-01", "star projection"],
  ["proj-02", "qualified t.* projection"],
  ["alias-01", "output alias usable in ORDER BY"],
  ["alias-02", "output alias usable in GROUP BY"],
  ["alias-03", "output alias not visible in WHERE"],
  ["dist-01", "DISTINCT dedups rows and NULLs"],
  ["diston-01", "DISTINCT ON picks first row per group"],
  ["diston-02", "DISTINCT ON with multiple expressions"],
  ["order-01", "ORDER BY mixed ASC and DESC"],
  ["order-02", "ORDER BY NULLS FIRST and NULLS LAST"],
  ["order-03", "ORDER BY expression"],
  ["order-04", "ORDER BY ordinal position"],
  ["order-05", "ORDER BY ordinal out of range errors"],
  ["limit-01", "LIMIT with OFFSET"],
  ["fetch-01", "OFFSET n ROWS FETCH NEXT n ROWS ONLY"],
  ["fetch-02", "FETCH FIRST n ROWS WITH TIES"],
  ["set-01", "UNION dedups across branches"],
  ["set-02", "UNION ALL keeps duplicates"],
  ["set-03", "INTERSECT"],
  ["set-04", "EXCEPT"],
  ["set-05", "set-op numeric type resolution"],
  ["set-06", "ORDER BY and LIMIT apply to whole compound"],
  ["set-07", "set-op column count mismatch errors"],
  ["values-01", "VALUES as a FROM table with aliases"],
  ["group-01", "GROUP BY expression"],
  ["group-02", "GROUP BY with HAVING"],
  ["group-03", "GROUPING SETS"],
  ["group-04", "ROLLUP"],
  ["group-05", "CUBE with grouping()"],
  ["having-01", "HAVING without GROUP BY"],
  ["sub-01", "scalar subquery in select list"],
  ["sub-02", "IN subquery"],
  ["sub-03", "correlated EXISTS subquery"],
  ["sub-04", "ANY and ALL subquery comparisons"],
  ["row-01", "row-value comparisons"],
  ["row-02", "row-value filter on table columns"],
  ["case-01", "CASE expression in projection"],
  ["talias-01", "table alias with column aliases"],
  ["corr-01", "correlated scalar subquery in projection"],
]);
