import { type CatalogSection, section } from "../scenario-types.ts";

const D = "documented_divergence" as const;

export const TOK_SECTION: CatalogSection = section("TOK", "Tokenizer & lexical layer", true, [
  ["kw-01", "Keywords are case-insensitive"],
  ["ident-01", "Quoted identifiers preserve case"],
  ["ident-02", "Embedded quotes in quoted identifiers"],
  ["ident-03", "Unquoted identifiers fold to lowercase"],
  ["ident-04", "Quoted keywords usable as identifiers"],
  ["ident-05", "Identifiers with $ and _"],
  ["ident-06", "Unicode identifiers"],
  ["ident-07", "Unknown quoted identifier is a column error"],
  ["str-01", "Standard string '' escape"],
  ["str-02", "String literal with embedded newline"],
  ["str-03", "Empty string literal"],
  ["str-04", "Newline-separated string literal concatenation"],
  ["str-05", "Backslash is literal in standard strings"],
  ["str-06", "Same-line adjacent string literals error"],
  ["str-07", "Unterminated string literal errors"],
  ["estr-01", "E-string tab and newline escapes"],
  ["estr-02", "E-string backslash escape"],
  ["estr-03", "E-string unicode escapes"],
  ["estr-04", "E-string hex and octal escapes"],
  ["dollar-01", "Dollar-quoted string $$..$$"],
  ["dollar-02", "Tagged dollar quotes including mixed-case tags"],
  ["dollar-03", "Multiline dollar-quoted string"],
  ["num-01", "Integer literals"],
  ["num-02", "Decimal literal forms"],
  ["num-03", "Scientific notation"],
  ["num-04", "Hexadecimal integer literals"],
  ["num-05", "Underscore digit separators"],
  ["num-06", "Binary and octal integer literals"],
  ["bytea-01", "Bytea hex literal"],
  ["cast-01", ":: cast operator"],
  ["cmt-01", "Line comments -- to EOL"],
  ["cmt-02", "Block comments /* */"],
  ["cmt-03", "Nested block comments"],
  ["cmt-04", "Comment-only script", D, "memory rejects a statement-free script as an empty statement; PostgreSQL accepts it"],
  ["op-01", "JSON arrow operator tokens -> and ->>"],
  ["op-02", "Containment operator token @>"],
  ["op-03", "Comparison operator tokens <> != <= >="],
  ["semi-01", "Trailing semicolon on a single query"],
  ["ws-01", "Tab and CRLF whitespace between tokens"],
  ["uesc-01", "U& unicode escape string"],
]);
