import { type CatalogSection, section } from "../scenario-types.ts";

export const TSR_SECTION: CatalogSection = section("TSR", "Full text search", true, [
  ["vec-01", "to_tsvector english stems and positions"],
  ["vec-02", "to_tsvector default config"],
  ["vec-03", "to_tsvector simple config keeps stop words"],
  ["vec-04", "repeated lexemes keep all positions"],
  ["vec-05", "to_tsvector of an empty string"],
  ["qry-01", "to_tsquery with AND"],
  ["qry-02", "to_tsquery with OR and NOT"],
  ["qry-03", "to_tsquery stems terms"],
  ["qry-04", "plainto_tsquery ANDs plain words"],
  ["qry-05", "phraseto_tsquery builds a phrase query"],
  ["lit-01", "tsvector literal cast"],
  ["lit-02", "tsvector literal with positions"],
  ["lit-03", "tsquery literal cast"],
  ["match-01", "@@ matches a stemmed word"],
  ["match-02", "@@ no match returns false"],
  ["match-03", "@@ with AND requires both terms"],
  ["match-04", "@@ with OR requires either term"],
  ["match-05", "@@ with NOT excludes matches"],
  ["match-06", "@@ over table rows"],
  ["cat-01", "tsvector || concatenation shifts positions"],
  ["op-01", "tsquery && combines with AND"],
  ["op-02", "tsquery || combines with OR"],
  ["op-03", "!! negates a tsquery"],
  ["phrase-01", "phrase operator <-> inside to_tsquery"],
  ["phrase-02", "phrase distance <2> matches exactly two apart"],
  ["weight-01", "setweight assigns a weight"],
  ["weight-02", "setweight combined with concatenation"],
  ["strip-01", "strip removes positions and weights"],
  ["len-01", "length counts distinct lexemes"],
  ["rank-01", "ts_rank for a simple match"],
  ["rank-02", "ts_rank ordering over table rows"],
  ["head-01", "ts_headline wraps matches in default markers"],
  ["head-02", "ts_headline with custom start and stop markers"],
]);
