import { type CatalogSection, section } from "../scenario-types.ts";

const D = "documented_divergence" as const;

export const TYP_SECTION: CatalogSection = section("TYP", "Scalar type system & casts", true, [
  ["bool-01", "Boolean literals and pg_typeof"],
  ["bool-02", "Boolean text input forms"],
  ["bool-03", "Invalid boolean text errors"],
  ["int-01", "Integer literal typing int2/int4/int8"],
  ["int-02", "int2 overflow errors"],
  ["int-03", "int4 overflow errors"],
  ["int-04", "int8 arithmetic overflow errors"],
  ["int-05", "Integer extremes round-trip"],
  ["int-06", "int8 min divided by -1 overflows"],
  ["float-01", "float4/float8 casts and typing"],
  ["float-02", "NaN and Infinity text forms"],
  ["float-03", "NaN comparison ordering"],
  [
    "float-04",
    "Float literal beyond float8 range",
    D,
    "memory saturates '1e400'::float8 to Infinity; PostgreSQL raises 22003 out of range",
    undefined,
    "float8-overflow-saturates",
  ],
  ["float-05", "float8 binary artifacts surface"],
  ["num-01", "Numeric literal typing and scale preservation"],
  ["num-02", "numeric(p,s) typmod rounding"],
  ["num-03", "Numeric field overflow errors"],
  ["num-04", "Numeric NaN"],
  ["num-05", "Numeric division result scale"],
  ["text-01", "varchar(n) insert overflow errors"],
  ["text-02", "varchar(n) cast truncates silently"],
  ["text-03", "char(n) blank padding"],
  ["text-04", "char(n) comparison ignores trailing blanks"],
  ["text-05", "char(n) cast truncation"],
  ["bytea-01", "Bytea hex round-trip"],
  ["bytea-02", "Text to bytea and back"],
  ["uuid-01", "UUID normalization to lowercase"],
  ["uuid-02", "Invalid UUID errors"],
  ["uuid-03", "Braced UUID input"],
  ["dt-01", "Date literal and typing"],
  ["dt-02", "Timestamp input forms"],
  ["dt-03", "timestamptz AT TIME ZONE"],
  ["dt-04", "Interval input forms including ISO 8601"],
  ["dt-05", "Out-of-range date errors"],
  ["unknown-01", "Unknown literal typing"],
  ["unknown-02", "Unknown literal resolved by column context"],
  ["pgt-01", "Arithmetic result types"],
  ["pgt-02", "Mixed-type promotion rules"],
  ["cast-01", "Invalid integer cast text errors"],
  ["cast-02", "Whitespace-tolerant integer parse"],
  ["cast-03", "numeric to int rounds half away from zero"],
  ["cast-04", "float8 to int rounds half to even"],
]);
