import { type CatalogSection, section } from "../scenario-types.ts";

export const WIN_SECTION: CatalogSection = section("WIN", "Window functions", true, [
  ["rank-01", "row_number over ORDER BY"],
  ["rank-02", "row_number partitioned"],
  ["rank-03", "rank with ties and gaps"],
  ["rank-04", "dense_rank without gaps"],
  ["rank-05", "percent_rank and cume_dist"],
  ["rank-06", "ntile even and uneven buckets"],
  ["rank-07", "empty OVER clause"],
  ["nav-01", "lag and lead defaults"],
  ["nav-02", "lag lead with offsets and default values"],
  ["nav-03", "lag lead reset at partition boundaries"],
  ["nav-04", "first_value"],
  ["nav-05", "last_value default frame vs full frame"],
  ["nav-06", "nth_value incl beyond partition"],
  ["nav-07", "navigation over non-int types"],
  ["aggw-01", "sum as running-total window"],
  ["aggw-02", "avg and count over partitions"],
  ["aggw-03", "min max as running windows"],
  ["aggw-04", "string_agg and array_agg as windows"],
  ["aggw-05", "FILTER on window aggregates"],
  ["frame-01", "ROWS BETWEEN preceding and current"],
  ["frame-02", "ROWS following and shorthand frames"],
  ["frame-03", "ROWS unbounded both directions"],
  ["frame-04", "centered moving average"],
  ["frame-05", "RANGE default includes peers"],
  ["frame-06", "RANGE with numeric offsets"],
  ["frame-07", "RANGE with interval offsets over dates"],
  ["frame-08", "GROUPS frames"],
  ["frame-09", "EXCLUDE CURRENT ROW"],
  ["frame-10", "EXCLUDE GROUP and EXCLUDE TIES"],
  ["frame-11", "EXCLUDE NO OTHERS explicit"],
  ["named-01", "named window reused by two functions"],
  ["named-02", "named window with PARTITION BY"],
  ["named-03", "named window refined with a frame"],
  ["named-04", "multiple named windows in one query"],
  ["multi-01", "multiple window functions in one SELECT"],
  ["multi-02", "window function in ORDER BY clause"],
  ["mix-01", "windows over GROUP BY aggregates"],
  ["mix-02", "window in subquery filtered outside"],
  ["err-01", "undefined named window errors"],
]);
