import { errorParity, parity, sequenceParity } from "../helpers.ts";

sequenceParity(
  "serial assigns sequential values",
  ["CREATE TABLE t (id serial, v text)"],
  [
    { sql: "INSERT INTO t (v) VALUES ('a')" },
    { sql: "INSERT INTO t (v) VALUES ('b'), ('c')" },
    { sql: "SELECT id, v FROM t ORDER BY id", query: true },
  ],
  { compareFinalState: true },
);

sequenceParity(
  "explicit serial value does not advance sequence",
  ["CREATE TABLE t (id serial, v text)"],
  [
    { sql: "INSERT INTO t (id, v) VALUES (100, 'explicit')" },
    { sql: "INSERT INTO t (v) VALUES ('auto')" },
    { sql: "SELECT id, v FROM t ORDER BY id", query: true },
  ],
  { compareFinalState: true },
);

sequenceParity(
  "bigserial assigns sequential values",
  ["CREATE TABLE t (id bigserial, v text)"],
  [{ sql: "INSERT INTO t (v) VALUES ('a'), ('b')" }, { sql: "SELECT id, v FROM t ORDER BY id", query: true }],
  { compareFinalState: true },
);

sequenceParity(
  "GENERATED ALWAYS AS IDENTITY auto-assigns",
  ["CREATE TABLE t (id int GENERATED ALWAYS AS IDENTITY, v text)"],
  [{ sql: "INSERT INTO t (v) VALUES ('a'), ('b')" }, { sql: "SELECT id, v FROM t ORDER BY id", query: true }],
  { compareFinalState: true },
);

sequenceParity(
  "GENERATED BY DEFAULT AS IDENTITY allows explicit values",
  ["CREATE TABLE t (id int GENERATED BY DEFAULT AS IDENTITY, v text)"],
  [
    { sql: "INSERT INTO t (v) VALUES ('auto1')" },
    { sql: "INSERT INTO t (id, v) VALUES (50, 'explicit')" },
    { sql: "INSERT INTO t (v) VALUES ('auto2')" },
    { sql: "SELECT id, v FROM t ORDER BY id", query: true },
  ],
  { compareFinalState: true },
);

sequenceParity(
  "OVERRIDING SYSTEM VALUE inserts explicit id",
  ["CREATE TABLE t (id int GENERATED ALWAYS AS IDENTITY, v text)"],
  [
    { sql: "INSERT INTO t (id, v) OVERRIDING SYSTEM VALUE VALUES (99, 'explicit')" },
    { sql: "SELECT id, v FROM t ORDER BY id", query: true },
  ],
  { compareFinalState: true },
);

parity(
  "identity RETURNING id",
  ["CREATE TABLE t (id int GENERATED ALWAYS AS IDENTITY, v text)"],
  "INSERT INTO t (v) VALUES ('a'), ('b') RETURNING id, v",
);

parity(
  "serial column omitted from column list",
  ["CREATE TABLE t (id serial, a int, b int)", "INSERT INTO t (a, b) VALUES (1, 2), (3, 4)"],
  "SELECT id, a, b FROM t ORDER BY id",
);

errorParity(
  "cannot insert into GENERATED ALWAYS identity without OVERRIDING",
  ["CREATE TABLE t (id int GENERATED ALWAYS AS IDENTITY, v text)"],
  "INSERT INTO t (id, v) VALUES (1, 'x')",
);

sequenceParity(
  "identity START WITH and INCREMENT BY",
  ["CREATE TABLE t (id int GENERATED ALWAYS AS IDENTITY (START WITH 10 INCREMENT BY 5), v text)"],
  [{ sql: "INSERT INTO t (v) VALUES ('a'), ('b'), ('c')" }, { sql: "SELECT id, v FROM t ORDER BY id", query: true }],
  { compareFinalState: true },
);
